# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodHub' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodHub
  pod 'IQKeyboardManagerSwift'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'MessageKit'
#  pod 'Firebase/Core'
#  pod 'Firebase/Database'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Firestore'
pod 'Alamofire'
pod 'AlamofireImage'

  target 'FoodHubTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodHubUITests' do
    # Pods for testing
  end

end
